### ISSUE TITLE
Close tags

### ISSUE THREAD

**Issue by alissonsv** [jseutter/ofxparse#165]
Hello everyone!
I'm using this library in a project to read and parse .ofx files. 

But the software that will import the .ofx after being write needs every tag to be closed, is there a way to do this?

Everything is working well, just need a way to close all the tags after use this function _OfxPrinter(ofx, file).write()_

**Comment by rdsteed** [comment]
I just saw this comment, hope this belated reply will be helpful.

OfxPrinter.py is basically a pretty printer for ofx files.

The ofxparse.py file in this project does include a preprocessor that inserts the missing close tags when importing ofx files.  See the master file at line 153:
`class OfxPreprocessedFile(OfxFile):`

In your code, your could use this preprocessed file rather than the original file as the input input to OfxPrint()

**Comment by alissonsv** [comment]
Thanks for your reply,
the way that I found to solve this was to use the ofxtools library that uses ElementTree, so I have a better control over each element.
