### ISSUE TITLE
Special char breaks parsing ?

### ISSUE THREAD

**Issue by waghanza** [jseutter/ofxparse#63]
Hi,

I use **OFX** format to deal with financial data. I've found this librariry to automate parsing (so this my first use of this **package**).

I try 

``` python
>>> import os
>>> from ofxparse import OfxParser
>>> file = open(os.path.expanduser('~/20131107.ofx'))
>>> ofx = OfxParser.parse(file)
```

but I have this traceback

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.3/site-packages/ofxparse/ofxparse.py", line 330, in parse
    ofx_file = OfxPreprocessedFile(file_handle)
  File "/usr/lib/python3.3/site-packages/ofxparse/ofxparse.py", line 141, in __init__
    super(OfxPreprocessedFile,self).__init__(fh)
  File "/usr/lib/python3.3/site-packages/ofxparse/ofxparse.py", line 71, in __init__
    self.read_headers()
  File "/usr/lib/python3.3/site-packages/ofxparse/ofxparse.py", line 77, in read_headers
    head_data = head_data[:head_data.find(six.b('<'))]
TypeError: Can't convert 'bytes' object to str implicitl
```

Is anybody ever had this bug ?

Regards,

**Comment by mattijs** [comment]
Hi, I'm just trying to bump this issue.

The little example from the README works great in python2 but I'm still seeing this error running python3 (3.5.1). The proposed solution (changing the line(s) to simple strings) works but is not really a fix. 

The problem is `six.b` returning a latin encoded byte string instead of a regular string for python3 (there is a PY3 check) that causes the error.

**Comment by mattijs** [comment]
Just a side note, opening the input file in binary mode (`rb`) fixes the problem. This should probably be mentioned as a requirement in the README.

**Comment by jseutter** [comment]
I updated README to open the file in binary mode. Thank you for reporting this.
